#! /bin/sh

# bspwmrc

# Starts compton (the window compositor) and sxhkd
compton &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Borders
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colours
bspc config normal_border_color		\#F7BE81
bspc config active_border_color 	\#FF4000
bspc config focused_border_color 	\#FF8000
bspc config border_width			5

# Rules for individual programs
bspc rule -a Steam desktop='^9' state=floating follow=off
